import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import { ItemCard } from "../components/ItemCard";
import { learningItemList } from "../data/items";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Courses</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/courses.tsx</code>
        </p>

        <div className={styles.grid}>
          {learningItemList?.map((item) => (
            <ItemCard key={item.id} item={item} />
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
