import type { NextPage } from "next";
import Head from "next/head";
import { learningItemList } from "../../data/items";
import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
  const guide = learningItemList[0];
  const guideChapter = guide.steps;

  return (
    <div className={styles.container}>
      <Head>
        <title>{`${guide.name} - ${guide.name}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{guide.name}</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>{`pages${guide.url}.tsx`}</code>
        </p>

        <div className={styles.grid}>
          {guideChapter?.map((chapter) => (
            <a key={chapter.id} href={chapter.url} className={styles.card}>
              <h2>{chapter.name} &rarr;</h2>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
