import type { NextPage } from "next";
import Head from "next/head";
import Footer from "@/components/Footer";
import { ItemStepCard } from "@/components/ItemStepCard";
import { learningItemList } from "@/data/items";
import { useLearningItemCompleteness } from "@/hooks/useLearningItemCompleteness";
import { useLearningItemState } from "@/hooks/useLearningItemState";
import styles from "@/styles/Home.module.css";

const Home: NextPage = () => {
  const guide = learningItemList[1];
  const guideChapter = guide.steps;

  const learningState = useLearningItemState(guide.id);
  const [completedStepsCount, allStepsCount] =
    useLearningItemCompleteness(learningState);

  return (
    <div className={styles.container}>
      <Head>
        <title>{`${guide.name} - ${guide.name}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{guide.name}</h1>

        <h2>
          Completed {completedStepsCount}/{allStepsCount}
        </h2>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>{`pages${guide.url}.tsx`}</code>
        </p>

        <div className={styles.grid}>
          {guideChapter?.map((chapter) => (
            <ItemStepCard key={chapter.id} item={guide} itemStep={chapter} />
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
